version: '3.8'
services:
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - "8081:80"
    volumes:
      - ./html/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  ngrok:
    image: wernight/ngrok
    depends_on:
      - nginx
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_PORT=nginx:80
    ports:
      - "4041:4040"