version: '3.8'
services:
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
