version: '3.8'
services:
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - "8081:80"
    volumes:
      - ./html/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
